<?php

/**
 * @file
 * Contains weather_api_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function weather_api_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the weather_api_entity module.
    case 'help.page.weather_api_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides entity for connection to external weather services.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function weather_api_entity_theme($existing, $type, $theme, $path) {
  return [
    'open_weather_map_entity_theme' => [
      'variables' => [
        'weather_details' => [],
      ],
    ],
    'weather_stack_entity_theme' => [
      'variables' => [
        'weather_details' => [],
      ],
    ],
  ];
}

/**
 * Set available templates options.
 *
 * @return array
 *   Return option list with available templates.
 */
function weather_api_entity_available_templates() {
  $available_templates = [
    'open_weather_map_entity_theme' => t('Open Weather Map'),
    'weather_stack_entity_theme' => t('Weather Stack'),
  ];

  Drupal::moduleHandler()->alter(['weather_api_entity_available_templates'], $available_templates);

  return $available_templates;
}
